# analytics
googleAnalytics = "UA-129126578-2"

baseURL = '/weblogic-toolikit-ui/'
languageCode = 'en-us'
title = 'WebLogic Kubernetes Toolkit UI'

# Change the default theme to be use when building the site with Hugo
theme = 'learn'

publishDir = "docs"

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]

[params]
  # disable the copy to clipboard links
  disableInlineCopyToClipBoard = true
